"""Generate include/generated/version.h from git metadata.

Runs as a PlatformIO ``pre:`` extra script. Falls back to a static version when
git is unavailable (e.g. building from a source tarball).
"""

import os
import subprocess
import datetime

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

FALLBACK_VERSION = "0.1.0"
PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
OUT_DIR = os.path.join(PROJECT_DIR, "include", "generated")
OUT_FILE = os.path.join(OUT_DIR, "version.h")


def _git(*args):
    try:
        return (
            subprocess.check_output(
                ["git"] + list(args), cwd=PROJECT_DIR, stderr=subprocess.DEVNULL
            )
            .decode("utf-8", "replace")
            .strip()
        )
    except Exception:
        return ""


def _version():
    described = _git("describe", "--tags", "--dirty", "--always")
    if not described:
        return FALLBACK_VERSION
    # v1.2.3-4-gabcdef  ->  1.2.3+4.gabcdef
    if described.startswith("v"):
        described = described[1:]
    return described


def main():
    version = _version()
    commit = _git("rev-parse", "--short", "HEAD") or "nogit"
    branch = _git("rev-parse", "--abbrev-ref", "HEAD") or "unknown"
    built = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    body = (
        "// Generated by tools/gen_version.py — do not edit, do not commit.\n"
        "#pragma once\n\n"
        '#define FW_VERSION      "{version}"\n'
        '#define FW_COMMIT       "{commit}"\n'
        '#define FW_BRANCH       "{branch}"\n'
        '#define FW_BUILD_DATE   "{built}"\n'
    ).format(version=version, commit=commit, branch=branch, built=built)

    os.makedirs(OUT_DIR, exist_ok=True)
    # Only rewrite when the meaningful part changed, otherwise every build would
    # invalidate the whole compilation unit graph via the timestamp.
    previous = ""
    if os.path.exists(OUT_FILE):
        with open(OUT_FILE, "r", encoding="utf-8") as fh:
            previous = fh.read()
    if _strip_date(previous) != _strip_date(body):
        with open(OUT_FILE, "w", encoding="utf-8") as fh:
            fh.write(body)

    print("firmware version %s (%s @ %s)" % (version, commit, branch))


def _strip_date(text):
    return "\n".join(
        line for line in text.splitlines() if "FW_BUILD_DATE" not in line
    )


main()
